apiVersion: v1
kind: Pod
metadata:
  name: image-imgservice
  labels:
    app: image-imgservice
spec:
  containers:
    - name: image-imgservice
      image: image-imgservice:latest
      imagePullPolicy: Never
      ports:
        - containerPort: 50051

---
apiVersion: v1
kind: Service
metadata:
  name: image-imgservice-svc
spec:
  selector:
    app: image-imgservice  # Match the label of the Pod
  ports:
    - protocol: TCP
      port: 50051           # Service port exposed to the cluster
      targetPort: 50051     # Target port inside the Pod (gRPC server)