apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    app: redis
spec:
  containers:
    - name: redis
      image: redis:alpine
      ports:
        - containerPort: 6379  # Redis default port

---
apiVersion: v1
kind: Service
metadata:
  name: redis-svc
spec:
  selector:
    app: redis  # Match the label of the Redis Pod
  ports:
    - protocol: TCP
      port: 6379      # Service port exposed to the cluster
      targetPort: 6379 # Target port inside the Redis container
